{% set name = "holodeck-gw" %}
{% set version = "1.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/holodeck-gw-{{ version }}.tar.gz
  sha256: bdffc3772361d6e7930b9de75e9b7233c83f309a6a2fc4cbd7770f9b08b08c62

build:
  skip: true  # [py<39 or win]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools >=40.6.0
    - wheel
    - cython <3.0.0
    - numpy <2.0.0
    - scipy
    - numba
    - pip
    - mpi4py
  run:
    - python
    - kalepy
    - astropy
    - cosmopy
    - h5py
    - matplotlib-base
    - scipy
    - pydoe
    - psutil
    - ipywidgets
    - tqdm
    - schwimmbad
    - emcee
    - george
    - numba
    - mpi4py
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - holodeck
  requires:
    - openssh  # [unix]

about:
  home: https://github.com/NANOGrav/holodeck/
  summary: 'holodeck: Massive black hole (MBH) binary simulator for pulsar timing array signals.'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - davecwright3
